### ISSUE TITLE
Thermo_GPUMD

### ISSUE THREAD

**Issue by ZengZezhu** [AlexGabourie/thermo#5]
Hi,

I just found that the hnemd_spectral_decomp function and the shc_load function have some bugs when running the python.

Ns = shc.shape[0]/Nc

if Ns is defined by below formula, then the Ns is a float number and cannot use it to define a array like: shc_in = np.reshape(shc[:,0], (Ns, Nc)).
Maybe we need one more sentence: Ns = int(Ns)

I also found the spectral calculation function has some problems about the unit and converter number, I think the unit of area parameter is angstrom**2, not nm**2.

**Comment by AlexGabourie** [comment]
Great catch! The first part is a problem coming from Python2 to Python3. I'll need to check the units for the second part.

**Comment by AlexGabourie** [comment]
The integer issue in shc_load should be fixed. I also updated the hnemd_spectral_decomp function. The units should now be correct. Let me know if I missed something. Otherwise, I will close this issue tomorrow.

**Comment by ZengZezhu** [comment]
Ok, thank you for your prompt response. 
I will check it again!

**Comment by ZengZezhu** [comment]
It seems that the units of  hnemd_spectral_decomp function still have some problems. 
If I use the new function, then the spectral kappa value is so small

**Comment by AlexGabourie** [comment]
Which version of GPUMD are you using? 

My change makes this code reflect the master branch of GPUMD. It follows the calculation of Eq. (21) of [Dr. Fan's HNEMD paper](https://journals.aps.org/prb/pdf/10.1103/PhysRevB.99.064308). Previously, the spectral heat current was calculated through a cross-sectional area. (Previously, my code processed the SHC output when used in conjunction with HNEMD.) The details of this are in the PDF manual of the v2.4 release of GPUMD. If you are using the latest release (v2.4), then I will have to make some edits for this function to work properly.

It's also possible I made another mistake. I will take a closer look at this tomorrow.

**Comment by ZengZezhu** [comment]
I used the latest version.
The unit of ki that read from the shc.out is eV/ps, and make a FFT from time domain to frequency domain. After making it, the unit of qi is eV?

**Comment by AlexGabourie** [comment]
Ok, great. The way I understand it, the units from ki are in (eV Angstrom)/ps. The function hnemd_spectral_decomp takes the discrete Fourier transform making qi units of (eV Angstrom)/ps/THz (i.e. the same as (eV Angstrom)). Then my updated conversion factor makes the output of that function be in W/m/K/THz. This way, when you integrate over all frequencies, nu, you get a thermal conductivity in W/m/K.

I have tested the updated hnemd_spectral_decomp and shc_load functions on the results of an HNEMD+SHC simulation of a graphene sheet and have gotten correct results. Also, if I integrate over all frequencies, I recover the full HNEMD thermal conductivity. 

Can you check to make sure that you are using the correct inputs and units for the hnemd_spectral_decomp and shc_load functions? Otherwise, I would need to see more about your specific case to figure out where the problem is.

**Comment by ZengZezhu** [comment]
Thanks a lot for your information!

I will test it and let you know the progress.

**Comment by ZengZezhu** [comment]
Hi,
when I used this hnemd_spectral_decomp function like below:

spe = hnemd_spectral_decomp(dt,Nc,Fmax,Fe,T,V,directory='.')

I encountered a bug like:

ValueError: Nc_conv must be an int. I am confused about this.

However, if I set up the df and Nc_conv by myself like:

spe = hnemd_spectral_decomp(dt,Nc,Fmax,Fe,T,V,df,Nc_conv, directory='.')

the result is correct!

I just had a look about the code of hnemd_spectral_decomp, and I think maybe the Nc_conv could set up a input parameter like Nc, then the user can have more choices.
How about your consideration?

**Comment by AlexGabourie** [comment]
Thank you for helping me with this. I think I finally have it worked out. When you run an SHC simulation, GPUMD outputs a correlation function up to a certain number of correlation steps. Before running simulations, it is unclear what a long enough correlation time is so, I usually calculate a very long correlation with a large Nc. Then, after the GPUMD runs, I look at the correlation function and decide what my Nc really should have been. This is what Nc_conv is supposed to represent. It should not be a required parameter because, if you chose Nc properly, you would not need to use it. 

I have updated the code to make Nc_conv optional and, if it is not defined, the Fourier transform of the full correlation output from GPUMD will be calculated.

Hopefully we won't need any more changes and it works the way you would like, but let me know if you find anything else. I'm glad to hear that you got a correct result!

**Comment by ZengZezhu** [comment]
Thank you so much for your effort, I really like it! It is very
convenient and efficient to do some post-process.

**Comment by AlexGabourie** [comment]
Thanks! There's a lot of stuff to add and work on, but I find it helps me quite a bit already.
